[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = "Leticia"
version = "0.1"
dependencies = [
	"click",
	"matplotlib",
	"numpy",
	"scipy",
]

[project.scripts]
leticia = "leticia.scripts:cli"
